### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [gouflv/react-papercss-ui#1]
It has been noticed that while using codecov/codecov-action@v1 your token 8c3c2818-0ec5-4f8a-8f4f-bc170ed0d86f is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by gouflv** [comment]
Thanks for your notice, codecov token is optional for this project, I plan to remove it.
